/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 15-jan-2018 01:47:54 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */
DROP DATABASE IF EXISTS
ist170940;
CREATE SCHEMA IF NOT EXISTS
ist170940;
USE ist170940;


SET FOREIGN_KEY_CHECKS=0 ;

/* Create Tables */

CREATE TABLE `Warehouse`
(
	`ID_Warehouse` VARCHAR(50) NOT NULL,
	`Location` VARCHAR(50) 	,
	`Capacity` INT 	,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID_Warehouse`)
);

CREATE TABLE `Produced`
(
	`ID_Plant` VARCHAR(50) 	,
	`ID_Farm` VARCHAR(50) 	,
	`ID_Warehouse` VARCHAR(50) 	,
	`Amount` INT 	,
	`Unit_Price` INT 	,
	`Date` DATE 	,
	CONSTRAINT `FK_Produced_Farm` FOREIGN KEY (`ID_Farm`) REFERENCES `Farm` (`ID_Farm`) ON DELETE Restrict ON UPDATE Restrict,
	CONSTRAINT `FK_Produced_Plant` FOREIGN KEY (`ID_Plant`) REFERENCES `Plant` (`ID_Plant`) ON DELETE Restrict ON UPDATE Restrict,
	CONSTRAINT `FK_Produced_Warehouse` FOREIGN KEY (`ID_Warehouse`) REFERENCES `Warehouse` (`ID_Warehouse`) ON DELETE Restrict ON UPDATE Restrict
)

;

CREATE TABLE `Plant`
(
	`ID_Plant` VARCHAR(50) NOT NULL,
	`Name` VARCHAR(50) 	,
	`Variety` VARCHAR(50) 	,
	`Type` VARCHAR(50) 	,
	`MST` INT 	,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID_Plant`)
)

;

CREATE TABLE `T_Order`
(
	`ID_Order` VARCHAR(50) NOT NULL,
	`Date` DATE 	,
	`Status` VARCHAR(50) 	,
	`Cost` INT 	,
	`ETA` INT 	,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID_Order`)
)

;

CREATE TABLE `Makes`
(
	`ID_Costumer` varchar(50) 	,
	`ID_Order` varchar(50) 	,
	CONSTRAINT `FK_Makes_Costumer` FOREIGN KEY (`ID_Costumer`) REFERENCES `Costumer` (`ID_Costumer`) ON DELETE Restrict ON UPDATE Restrict,
	CONSTRAINT `FK_Makes_Order` FOREIGN KEY (`ID_Order`) REFERENCES `Order` (`ID_Order`) ON DELETE Restrict ON UPDATE Restrict
)

;

CREATE TABLE `Include`
(
	`ID_Order` VARCHAR(50) 	,
	`ID_Plant` VARCHAR(50) 	,
	`ID_Farm` VARCHAR(50) 	,
	`ID_Warehouse` VARCHAR(50) 	,
	`Amount` VARCHAR(50) 	,
	CONSTRAINT `FK_Include_Order` FOREIGN KEY (`ID_Order`) REFERENCES `Order` (`ID_Order`) ON DELETE Restrict ON UPDATE Restrict,
	CONSTRAINT `FK_Include_Produced_Farm` FOREIGN KEY (`ID_Farm`) REFERENCES `Farm` (`ID_Farm`) ON DELETE Restrict ON UPDATE Restrict,
	CONSTRAINT `FK_Include_Produced_Plant` FOREIGN KEY (`ID_Plant`) REFERENCES `Plant` (`ID_Plant`) ON DELETE Restrict ON UPDATE Restrict,
	CONSTRAINT `FK_Include_Produced_Warehouse` FOREIGN KEY (`ID_Warehouse`) REFERENCES `Warehouse` (`ID_Warehouse`) ON DELETE Restrict ON UPDATE Restrict
)
;

CREATE TABLE `Farm`
(
	`ID_Farm` VARCHAR(50) NOT NULL,
	`Name` VARCHAR(50) 	,
	`Address` VARCHAR(50) 	,
	`Owner` VARCHAR(50) 	,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID_Farm`)
)

;

CREATE TABLE `Costumer`
(
	`ID_Costumer` varchar(50) NOT NULL,
	`Name` varchar(50) 	,
	`Mail` varchar(50) 	,
	`Phone` varchar(50) 	,
	`Address` varchar(50) 	,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID_Costumer`)
)

;

SET FOREIGN_KEY_CHECKS=1 ;

-- Populate Tables
-- "C:\Users\David\Documents\GitHub\POBD\mysql\CSV\Order.csv"

load data local infile 'C:\\Users\\David\\Documents\\GitHub\\POBD\\mysql\\CSV\\Warehouse.csv'
into table Warehouse  
fields terminated by ','
lines terminated by '\r\n'
IGNORE 1 ROWs;

load data local infile 'C:\\Users\\David\\Documents\\GitHub\\POBD\\mysql\\CSV\\Costumer.csv'
into table Costumer
fields terminated by ','
lines terminated by '\r\n'
IGNORE 1 ROWs;


load data local infile 'C:\\Users\\David\\Documents\\GitHub\\POBD\\mysql\\CSV\\Plant.csv'
into table Plant
fields terminated by ','
lines terminated by '\r\n'
IGNORE 1 ROWs;

load data local infile 'C:\\Users\\David\\Documents\\GitHub\\POBD\\mysql\\CSV\\Order.csv'
into table T_Order
fields terminated by ','
lines terminated by '\r\n'
IGNORE 1 ROWs;

load data local infile 'C:\\Users\\David\\Documents\\GitHub\\POBD\\mysql\\CSV\\r_Produced.csv'
into table Produced
fields terminated by ','
lines terminated by '\r\n'
IGNORE 1 ROWs;

load data local infile 'C:\\Users\\David\\Documents\\GitHub\\POBD\\mysql\\CSV\\Farm.csv'
into table Farm
fields terminated by ','
lines terminated by '\r\n'
IGNORE 1 ROWs;

load data local infile 'C:\\Users\\David\\Documents\\GitHub\\POBD\\mysql\\CSV\\r_makes.csv'
into table Makes 
fields terminated by ','
lines terminated by '\r\n'
IGNORE 1 ROWs;

load data local infile 'C:\\Users\\David\\Documents\\GitHub\\POBD\\mysql\\CSV\\r_include.csv'
into table Include
fields terminated by ','
lines terminated by '\r\n'
IGNORE 1 ROWs;


select * from Plant


/*
load data local infile 'C:\\Users\\Manuel\\CSV\\Costumer.csv' 
into table Costumer
fields terminated by ';'
lines terminated by '\r\n';

load data local infile 'C:\\Users\\Manuel\\CSV\\Farm.csv' 
into table Farm 
fields terminated by ';'
lines terminated by '\r\n';

load data local infile 'C:\\Users\\Manuel\\CSV\\Warehouse.csv' 
into table Warehouse 
fields terminated by ';'
lines terminated by '\r\n';
load data local infile 'C:\\Users\\Manuel\\CSV\\Order.csv' 
into table `Order`
fields terminated by ';'
lines terminated by '\r\n';

load data local infile 'C:\\Users\\Manuel\\CSV\\r_Produced.csv' 
into table Produced
fields terminated by ';'
lines terminated by '\r\n';

load data local infile 'C:\\Users\\Manuel\\CSV\\r_include.csv' 
into table Include
fields terminated by ';'
lines terminated by '\r\n';

load data local infile 'C:\\Users\\Manuel\\CSV\\r_makes.csv' 
into table Makes
fields terminated by ';'
lines terminated by '\r\n';
*/