/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 18-jan-2018 00:50:15 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 ;

/* Create Tables */

CREATE TABLE `Warehouse`
(
	`ID_Warehouse` VARCHAR(50) NOT NULL,
	`Location` VARCHAR(50) 	,
	`Capacity` INT 	,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID_Warehouse`)
)

;

CREATE TABLE `T_Order`
(
	`ID_Order` VARCHAR(50) NOT NULL,
	`Date` DATE 	,
	`Status` VARCHAR(50) 	,
	`Cost` INT 	,
	`ETA` INT 	,
	CONSTRAINT `Order` PRIMARY KEY (`ID_Order`)
)

;

CREATE TABLE `Produced`
(
	`ID_Plant` VARCHAR(50) 	,
	`ID_Farm` VARCHAR(50) 	,
	`ID_Warehouse` VARCHAR(50) 	,
	`Amount` INT 	,
	`Unit_Price` INT 	,
	`Date` DATE 	
)

;

CREATE TABLE `Plant`
(
	`ID_Plant` VARCHAR(50) NOT NULL,
	`Name` VARCHAR(50) 	,
	`Variety` VARCHAR(50) 	,
	`Type` VARCHAR(50) 	,
	`MST` INT 	,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID_Plant`)
)

;

CREATE TABLE `Makes`
(
	`ID_Costumer` VARCHAR(50) NOT NULL,
	`ID_Order` VARCHAR(50) NOT NULL
)

;

CREATE TABLE `Include`
(
	`ID_Order` VARCHAR(50) 	,
	`ID_Plant` VARCHAR(50) 	,
	`ID_Farm` VARCHAR(50) 	,
	`ID_Warehouse` VARCHAR(50) 	,
	`Amount` VARCHAR(50) 	
)

;

CREATE TABLE `Farm`
(
	`ID_Farm` VARCHAR(50) NOT NULL,
	`Name` VARCHAR(50) 	,
	`Address` VARCHAR(50) 	,
	`Owner` VARCHAR(50) 	,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`ID_Farm`)
)

;

CREATE TABLE `Costumer`
(
	`ID_Costumer` VARCHAR(50) NOT NULL,
	`Name` VARCHAR(50) 	,
	`Mail` VARCHAR(50) 	,
	`Phone` VARCHAR(50) 	,
	`Address` VARCHAR(50) 	,
	CONSTRAINT `Costumer` PRIMARY KEY (`ID_Costumer`)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Produced` 
 ADD CONSTRAINT `FK_Produced_Farm`
	FOREIGN KEY (`ID_Farm`) REFERENCES `Farm` (`ID_Farm`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Produced` 
 ADD CONSTRAINT `FK_Produced_Plant`
	FOREIGN KEY (`ID_Plant`) REFERENCES `Plant` (`ID_Plant`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Produced` 
 ADD CONSTRAINT `FK_Produced_Warehouse`
	FOREIGN KEY (`ID_Warehouse`) REFERENCES `Warehouse` (`ID_Warehouse`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Makes` 
 ADD CONSTRAINT `FK_Makes_Costumer`
	FOREIGN KEY (`ID_Costumer`) REFERENCES `Costumer` (`ID_Costumer`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Makes` 
 ADD CONSTRAINT `FK_Makes_T_Order`
	FOREIGN KEY (`ID_Order`) REFERENCES `T_Order` (`ID_Order`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Include` 
 ADD CONSTRAINT `FK`
	FOREIGN KEY () REFERENCES  () ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 ;
